version: '3.8'
services:
  plm-backend:
    hostname: "plm"
    build: .
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    environment:
      PORT_PLM_BACKEND: "3000"
      HOST_DB: "127.0.0.1"
      DB_USER: "${DB_USER}"
      DB_PWD: "${DB_PWD}"
      DB_NAME: "${DB_NAME}"
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo:5.0.5
    container_name: mongo
    restart: always
    environment:
      MONGO_DATA_DIR: "/data/db"
      MONGO_LOG_DIR: "/dev/db/log"
      MONGO_INITDB_DATABASE: "${DB_NAME}"
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    ports:
      - "49152:27017"
    volumes:
      - mongodb_server_data:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
volumes:
  mongodb_server_data: