version: "3.9"

volumes:
  plm_data:
    driver: local

services:
  web:
    container_name: plm_service
    image: aldominasi/plm:latest
    build: .
    environment:
      - PORT_PLM_BACKEND=${PORT_PLM_BACKEND}
      - MONGO_DB_HOST=db
      - DB_USER=${MONGO_INITDB_ROOT_USERNAME}
      - DB_PWD=${MONGO_INITDB_ROOT_PASSWORD}
      - DB_NAME=${MONGO_INITDB_DATABASE}
    depends_on:
      - db
    ports:
      - "3000:3000"
    links:
      - db
  db:
    image: mongo:5.0.5
    container_name: mongodb_plm
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    command: [ "--bind_ip_all" ]
    ports:
      - "49152:27017"
    volumes:
      - plm_data:/data/db
      - ./conf/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./initCollections/ruolis.json:/app/initCollections/ruolis.json
      - ./initCollections/utentis.json:/app/initCollections/utentis.json
    env_file:
      - .env